package controller;

public enum Actions {

	OK,
	EXIT,
	REGISTER_PATIENT,
	REGISTER_DOCTOR,
	LOGIN_PATIENT,
	LOGIN_DOCTOR,
	ADD_APPOINTMENT,
	DELETE_APPOINTMENT,
	CANCEL_APPOINTMENT,
	BOOK_APPOINTMENT,
	SHOW_APPOINTMENT_PATIENT,
	SHOW_APPOINTMENT_DOCTOR,
	SHOW_APPOINTMENT_PATIENT_STATUS,
	SHOW_APPOINTMENT_DOCTOR_STATUS,
	SHOW_APPOINTMENT,
	ATTEND_APPOINTMENT, 
	BTN_LOGIN_PATIENT, BTN_LOGIN_DOCTOR, BTN_SIGNUP_PATIENT, BTN_SIGNUP_DOCTOR
}
